export const GET_USER_SUCCESS = 'user/GET_USER/SUCCESS';
export const GET_USER_LOADING = 'user/GET_USER/LOADING';
export const GET_USER_ERROR = 'user/GET_USER/ERROR';

export const GET_ALL_USER_LOADING = 'user/GET_ALL_USER/LOADING';
export const GET_ALL_USER_SUCCESS = 'user/GET_ALL_USER/SUCCESS';
export const GET_ALL_USER_ERROR = 'user/GET_ALL_USER/ERROR';

export const GET_ALL_USER_THAT_I_DONT_FOLLOW_LOADING = 'user/GET_DONT_FOLLOW_USERS/LOADING';
export const GET_ALL_USER_THAT_I_DONT_FOLLOW_SUCCESS = 'user/GET_DONT_FOLLOW_USERS/SUCCESS';
export const GET_ALL_USER_THAT_I_DONT_FOLLOW_ERROR = 'user/GET_DONT_FOLLOW_USERS/ERROR';
