"""empty message

Revision ID: 244f2daa55d3
Revises: 1527959d23e6
Create Date: 2021-12-16 15:58:09.101683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244f2daa55d3'
down_revision = '1527959d23e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('s3Name', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 's3Name')
    # ### end Alembic commands ###
