"""empty message

Revision ID: 1527959d23e6
Revises: ffdc0a98111c
Create Date: 2021-12-16 15:57:18.413447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1527959d23e6'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('personDoingTheFollowing', sa.Integer(), nullable=False),
    sa.Column('personReceivingTheFollowing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personDoingTheFollowing'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personReceivingTheFollowing'], ['users.id'], ),
    sa.PrimaryKeyConstraint('personDoingTheFollowing', 'personReceivingTheFollowing')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('videoURL', sa.String(length=2000), nullable=False),
    sa.Column('s3Name', sa.String(length=2000), nullable=True),
    sa.Column('videoType', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('music', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('videoId', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videoHashtags',
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.Column('hashtagId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtagId'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('videoId', 'hashtagId')
    )
    op.create_table('videoLikes',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('videoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['videoId'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('userId', 'videoId')
    )
    op.create_table('commentLikes',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('commentId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commentId'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userId', 'commentId')
    )
    op.add_column('users', sa.Column('fullname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('photoURL', sa.String(length=2000), nullable=False))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['fullname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'photoURL')
    op.drop_column('users', 'fullname')
    op.drop_table('commentLikes')
    op.drop_table('videoLikes')
    op.drop_table('videoHashtags')
    op.drop_table('comments')
    op.drop_table('videos')
    op.drop_table('followers')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
